### ISSUE TITLE
ImportError: cannot import name 'quote'

### ISSUE THREAD

**Issue by geetheshtg** [YouTubeDownload/YouTubeDownload#19]
If I try to run the script it says 
    from pytube.compat import quote
ImportError: cannot import name 'quote'

**Comment by jslay88** [comment]
You are going to have to provide more useful information.

Trace stack, OS, Python version, pytube version installed.

**Comment by geetheshtg** [comment]
> You are going to have to provide more useful information.
> 
> Trace stack, OS, Python version, pytube version installed.

Traceback (most recent call last):
  File "script.py", line 6, in <module>
    from pytube import YouTube
  File "/home/geethesh/.local/lib/python3.6/site-packages/pytube/__init__.py", line 16, in <module>
    from pytube.streams import Stream
  File "/home/geethesh/.local/lib/python3.6/site-packages/pytube/streams.py", line 17, in <module>
    from pytube import extract
  File "/home/geethesh/.local/lib/python3.6/site-packages/pytube/extract.py", line 7, in <module>
    from pytube.compat import quote
ImportError: cannot import name 'quote'

Python version: 3.6.9

pytube version 9.5.5

**Comment by jslay88** [comment]
You are using an old version of pytube.

Update your requirements.
