### ISSUE TITLE
Too many values to unpack

### ISSUE THREAD

**Issue by usama2762** [YouTubeDownload/YouTubeDownload#24]
I have been using this but since the last few days it is giving me this error

```
Traceback (most recent call last):
  File "script.py", line 128, in <module>
    interactive_mode()
  File "script.py", line 51, in interactive_mode
    download_youtube_video(url, output_path='videos/')
  File "/Users/apple/Desktop/Development/DBZ/YouTubeDownload/download_youtube_video.py", line 35, in download_youtube_video
    video = YouTube(url)
  File "/Users/apple/.local/share/virtualenvs/YouTubeDownload-eRALDVo2/lib/python3.7/site-packages/pytube/__main__.py", line 92, in __init__
    self.descramble()
  File "/Users/apple/.local/share/virtualenvs/YouTubeDownload-eRALDVo2/lib/python3.7/site-packages/pytube/__main__.py", line 140, in descramble
    apply_signature(self.player_config_args, fmt, self.js)
  File "/Users/apple/.local/share/virtualenvs/YouTubeDownload-eRALDVo2/lib/python3.7/site-packages/pytube/extract.py", line 225, in apply_signature
    cipher = Cipher(js=js)
  File "/Users/apple/.local/share/virtualenvs/YouTubeDownload-eRALDVo2/lib/python3.7/site-packages/pytube/cipher.py", line 31, in __init__
    var, _ = self.transform_plan[0].split(".")
ValueError: too many values to unpack (expected 2)
```

**Comment by jslay88** [comment]
Looks like YouTube has changed something within the cipher/signature aspect. Unfortunately (as your can see with your Traceback), the issue lies within the pytube3 library, and the JS skills required to monkey patch/open a PR is beyond my capabilities/time. 

I also see that it looks like the maintainer for pytube3 is abandoned the project as well, so we might not be getting a fix anytime soon. 😢

**Comment by jslay88** [comment]
It looks like YouTube has resolved whatever issue there was on their end. I am able to download videos again without issue. Are you still seeing this issue?
